// Campos de Cabeçalho
export const fieldscab = [
  {
    id: 1000,
    campo: 'TB02303_OBS',
    funcao: 'Observações',
    tipo: 'text',
    nome: 'obs',
    tipoobject: 6,
    tamanho: 10,
    widthfield: 10,
    measure: '10rem',
    lines: 10
  }
];

// Campos de Exibiçao (Listagem Produtos)
export const fieldsitem = [
  {
    id: 0,
    campo: 'produto',
    funcao: 'Código',
    tipo: 'varchar',
    nome: 'produto',
    tamanho: 5,
    tipoobject: 1,
    widthfield: 6,
    measure: '6rem',
    disabled: true
  },
  {
    id: 1,
    campo: 'referencia',
    funcao: 'Referência',
    tipo: 'varchar',
    nome: 'referencia',
    tamanho: 20,
    tipoobject: 1,
    widthfield: 14,
    measure: '15rem',
    disabled: true
  },
  {
    id: 2,
    campo: 'codbarras',
    funcao: 'Código Barras',
    tipo: 'varchar',
    nome: 'codbarras',
    tamanho: 20,
    tipoobject: 1,
    widthfield: 18,
    measure: '18rem',
    disabled: true
  },
  {
    id: 3,
    campo: 'codauxiliar',
    funcao: 'Código Auxiliar',
    tipo: 'varchar',
    nome: 'codauxiliar',
    tamanho: 20,
    tipoobject: 1,
    widthfield: 18,
    measure: '17rem',
    disabled: true
  },
  {
    id: 4,
    campo: 'nomeun',
    funcao: 'UN',
    tipo: 'varchar',
    nome: 'codauxiliar',
    tamanho: 20,
    tipoobject: 1,
    widthfield: 6,
    measure: '6rem',
    disabled: true
  },
  {
    id: 5,
    campo: 'ncm',
    funcao: 'NCM',
    tipo: 'varchar',
    nome: 'ncm',
    tamanho: 20,
    tipoobject: 1,
    widthfield: 11,
    measure: '11rem',
    disabled: true
  },
  {
    id: 6,
    campo: 'nomeprod',
    funcao: 'Descrição Produto',
    tipo: 'varchar',
    nome: 'nomeprod',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 60,
    measure: '60rem',
    disabled: true
  },
  {
    id: 7,
    campo: 'prateleira',
    funcao: 'Prateleira',
    tipo: 'varchar',
    nome: 'prateleira',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 13,
    measure: '13rem',
    disabled: true
  },
  {
    id: 8,
    campo: 'nomemarca',
    funcao: 'Descrição Marca',
    tipo: 'varchar',
    nome: 'nomemarca',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 38,
    measure: '38rem',
    disabled: true
  },
  {
    id: 9,
    campo: 'qtprod',
    funcao: 'Quantidade',
    tipo: 'varchar',
    nome: 'qtprod',
    tamanho: 60,
    tipoobject: 4,
    widthfield: 10,
    measure: '11rem',
    disabled: true,
    decimal: 3
  },
  {
    id: 10,
    campo: 'prunit',
    funcao: 'Preço Unitário',
    tipo: 'varchar',
    nome: 'prunit',
    tamanho: 60,
    tipoobject: 4,
    widthfield: 10,
    measure: '12rem',
    disabled: true,
    decimal: 2
  },
  {
    id: 11,
    campo: 'vlrfinal',
    funcao: 'Valor Total',
    tipo: 'varchar',
    nome: 'vlrfinal',
    tamanho: 60,
    tipoobject: 4,
    widthfield: 10,
    measure: '12rem',
    disabled: true,
    decimal: 2
  },
  {
    id: 12,
    campo: 'nomegrupo',
    funcao: 'Descrição Grupo',
    tipo: 'varchar',
    nome: 'nomegrupo',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 25,
    measure: '25rem',
    disabled: true
  },
  {
    id: 13,
    campo: 'nomesubgrupo',
    funcao: 'Descrição Sub-Grupo',
    tipo: 'varchar',
    nome: 'nomesubgrupo',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 25,
    measure: '25rem',
    disabled: true
  },
  {
    id: 14,
    campo: 'nomelocal',
    funcao: 'Local de Armazenamento',
    tipo: 'varchar',
    nome: 'nomelocal',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 23,
    measure: '23rem',
    disabled: true
  }
];

// Colunas nas Listagem (Produtos)
export const columnsitem = [
  { headerClassName: 'header-list', field: 'produto', headerName: 'Código', width: 70 },
  { headerClassName: 'header-list', field: 'referencia', headerName: 'Referência', width: 137 },
  { headerClassName: 'header-list', field: 'nomeprod', headerName: 'Descrição do Produto', width: 463 },
  { headerClassName: 'header-list', field: 'qtprod', headerName: 'Quantidade', width: 115, type: 'number', decimal: 3 },
  { headerClassName: 'header-list', field: 'prunit', headerName: 'Preço Unitário', width: 115, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'perdesc', headerName: '% Desc.', width: 85, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'icms', headerName: '% ICMS', width: 85, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'percipi', headerName: '% IPI', width: 85, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'percst', headerName: '% ST', width: 85, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'vlrfrete', headerName: 'Frete', width: 85, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'vlroutdesp', headerName: 'Desp.', width: 85, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'vlrfinal', headerName: 'Valor Total', width: 115, type: 'number', decimal: 2 }
];

// Campos de Exibiçao (Lançamento Produtos)
export const fieldslanc = [
  {
    id: 0,
    campo: 'produto',
    funcao: 'Código',
    tipo: 'varchar',
    nome: 'produto',
    tamanho: 5,
    tipoobject: 1,
    widthfield: 6,
    measure: '6rem',
    disabled: true
  },
  {
    id: 1,
    campo: 'referencia',
    funcao: 'Referência',
    tipo: 'varchar',
    nome: 'referencia',
    tamanho: 20,
    tipoobject: 1,
    widthfield: 15,
    measure: '15rem',
    disabled: true
  },
  {
    id: 2,
    campo: 'codbarras',
    funcao: 'Código Barras',
    tipo: 'varchar',
    nome: 'codbarras',
    tamanho: 20,
    tipoobject: 1,
    widthfield: 15,
    measure: '15rem',
    disabled: true
  },
  {
    id: 3,
    campo: 'codauxiliar',
    funcao: 'Código Auxiliar',
    tipo: 'varchar',
    nome: 'codauxiliar',
    tamanho: 20,
    tipoobject: 1,
    widthfield: 15,
    measure: '15rem',
    disabled: true
  },
  {
    id: 4,
    campo: 'nomeprod',
    funcao: 'Descrição Produto',
    tipo: 'varchar',
    nome: 'nomeprod',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 51,
    measure: '51rem',
    disabled: true
  },
  {
    id: 5,
    campo: 'nomemarca',
    funcao: 'Descrição Marca',
    tipo: 'varchar',
    nome: 'nomemarca',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 17,
    measure: '17rem',
    disabled: true
  },
  {
    id: 6,
    campo: 'nomegrupo',
    funcao: 'Descrição Grupo',
    tipo: 'varchar',
    nome: 'nomegrupo',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 17,
    measure: '17rem',
    disabled: true
  },
  {
    id: 7,
    campo: 'nomesubgrupo',
    funcao: 'Descrição Sub-Grupo',
    tipo: 'varchar',
    nome: 'nomesubgrupo',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 17,
    measure: '17rem',
    disabled: true
  }
];

// Campos de Exibiçao (Impostos Produtos)
export const fieldsimp = [
  {
    id: 0,
    campo: 'qtprod',
    funcao: 'Quantidade',
    tipo: 'numeric',
    nome: 'qtprod',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 10,
    measure: '10rem',
    disabled: true,
    decimal: 3,
    lancfield: true
  },
  {
    id: 1,
    campo: 'tabela',
    funcao: 'Tabela Preços',
    tipo: 'varchar',
    nome: 'operacao',
    tipoobject: 2,
    tamanho: 2,
    widthfield: 36,
    measure: '36rem',
    tabelaref: 'TB01020',
    widthname: 27,
    disabled: true,
    lancfield: true
    /*filteraux:
      " AND TB01022_REMESSA = 'S' AND TB01022_CODIGO IN (SELECT TB01046_TIPODESC FROM TB01046 WHERE TB01046_CODEMP = '" +
      props.codemp +
      "') "*/
  },
  {
    id: 2,
    campo: 'prunit',
    funcao: 'Preço Unitário',
    tipo: 'numeric',
    nome: 'prunit',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 10,
    measure: '10rem',
    disabled: true,
    decimal: 2,
    lancfield: true
  },
  {
    id: 3,
    campo: 'nomeun',
    funcao: 'Unidade Medida',
    tipo: 'varchar',
    nome: 'nomeun',
    tamanho: 60,
    tipoobject: 1,
    widthfield: 10,
    measure: '10rem',
    disabled: true,
    lancfield: false
  },
  {
    id: 4,
    campo: 'perdesc',
    funcao: '% Desconto',
    tipo: 'numeric',
    nome: 'perdesc',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: true,
    decimal: 2,
    lancfield: true
  },
  {
    id: 5,
    campo: 'icms',
    funcao: '% ICMS',
    tipo: 'numeric',
    nome: 'icms',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: true,
    decimal: 2,
    lancfield: false
  },
  {
    id: 6,
    campo: 'percipi',
    funcao: '% IPI',
    tipo: 'numeric',
    nome: 'percipi',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: true,
    decimal: 2,
    lancfield: false
  },
  {
    id: 7,
    campo: 'percst',
    funcao: '% ST',
    tipo: 'numeric',
    nome: 'percst',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: true,
    decimal: 2,
    lancfield: false
  },
  {
    id: 8,
    campo: 'vlrfrete',
    funcao: 'Valor Frete',
    tipo: 'numeric',
    nome: 'vlrfrete',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: true,
    decimal: 2,
    lancfield: true
  },
  {
    id: 9,
    campo: 'vlroutdesp',
    funcao: 'Outras Despesas',
    tipo: 'numeric',
    nome: 'vlroutdesp',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: true,
    decimal: 2,
    lancfield: true
  }
];

// Campos de Arredondamento (Produtos)
export const fieldsarredonda = [
  {
    id: 0,
    campo: 'vlrdesc',
    funcao: 'Valor Desconto',
    tipo: 'numeric',
    nome: 'vlrdesc',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 1,
    campo: 'baseicms',
    funcao: 'Base de Cálculo ICMS',
    tipo: 'numeric',
    nome: 'baseicms',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 2,
    campo: 'vlricms',
    funcao: 'Valor do ICMS',
    tipo: 'numeric',
    nome: 'vlricms',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 3,
    campo: 'vlrbcipi',
    funcao: 'Base de Cálculo IPI',
    tipo: 'numeric',
    nome: 'vlrbcipi',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 4,
    campo: 'vlripi',
    funcao: 'Valor IPI',
    tipo: 'numeric',
    nome: 'vlripi',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 5,
    campo: 'basest',
    funcao: 'Base de Cálculo ST',
    tipo: 'numeric',
    nome: 'basest',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 6,
    campo: 'vlrst',
    funcao: 'Valor ST',
    tipo: 'numeric',
    nome: 'vlrst',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 7,
    campo: 'icmsdentro',
    funcao: 'ICMS Interno',
    tipo: 'numeric',
    nome: 'icmsdentro',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 8,
    campo: 'vlrfrete',
    funcao: 'Valor Frete',
    tipo: 'numeric',
    nome: 'vlrfrete',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 9,
    campo: 'vlroutdesp',
    funcao: 'Valor Outras Despesas',
    tipo: 'numeric',
    nome: 'vlroutdesp',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 10,
    campo: 'vlricmsdif',
    funcao: 'ICMS Diferimento',
    tipo: 'numeric',
    nome: 'vlricmsdif',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 11,
    campo: 'vlricmsdeson',
    funcao: 'ICMS Desonerado',
    tipo: 'numeric',
    nome: 'vlricmsdeson',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 12,
    campo: 'icmsfora',
    funcao: 'ICMS Interestadual',
    tipo: 'numeric',
    nome: 'icmsfora',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 13,
    campo: 'vlricmsfora',
    funcao: 'R$ ICMS Interestadual',
    tipo: 'numeric',
    nome: 'vlricmsfora',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 14,
    campo: 'vlrdifaliq',
    funcao: 'Diferencial Aliquota',
    tipo: 'numeric',
    nome: 'vlrdifaliq',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 15,
    campo: 'fcp',
    funcao: '% FCP',
    tipo: 'numeric',
    nome: 'fcp',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 16,
    campo: 'vlrfcp',
    funcao: 'R$ FCP Destino',
    tipo: 'numeric',
    nome: 'vlrfcp',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 17,
    campo: 'partilhaint',
    funcao: '% Partilha Origem',
    tipo: 'numeric',
    nome: 'partilhaint',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 18,
    campo: 'partilhaext',
    funcao: '% Partilha Destino',
    tipo: 'numeric',
    nome: 'partilhaext',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 19,
    campo: 'basefcptot',
    funcao: 'Base de Cálculo FCP',
    tipo: 'numeric',
    nome: 'basefcptot',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 20,
    campo: 'vlrfcptot',
    funcao: 'Valor FCP',
    tipo: 'numeric',
    nome: 'vlrfcptot',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 21,
    campo: 'basefcptotst',
    funcao: 'Base de Cálculo FCP ST',
    tipo: 'numeric',
    nome: 'basefcptotst',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  },
  {
    id: 22,
    campo: 'vlrfcptotst',
    funcao: 'Valor FCP ST',
    tipo: 'numeric',
    nome: 'vlrfcptotst',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    disabled: false,
    decimal: 2,
    lancfield: true
  }
];

// Colunas nas Listagem (Serviços)
export const columnsserv = [
  { headerClassName: 'header-list', field: 'codserv', headerName: 'Código', width: 70 },
  { headerClassName: 'header-list', field: 'nomeserv', headerName: 'Descrição do Serviço', width: 583 },
  { headerClassName: 'header-list', field: 'codtributacao', headerName: 'Cód. Tributação', width: 120 },
  { headerClassName: 'header-list', field: 'subitem', headerName: 'Sub-Item', width: 80 },
  { headerClassName: 'header-list', field: 'qtserv', headerName: 'Quantidade', width: 125, type: 'number' },
  { headerClassName: 'header-list', field: 'prunit', headerName: 'Preço Unitário', width: 135, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'totvalor', headerName: 'Valor Bruto', width: 135, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'vlrretencoes', headerName: 'Valor Retenções', width: 135, type: 'number', decimal: 2 },
  { headerClassName: 'header-list', field: 'total', headerName: 'Valor Total.', width: 135, type: 'number', decimal: 2 }
];

// Campos de Exibiçao (Impostos Serviços)
export const fieldsimpserv = [
  {
    id: 0,
    campo: 'codserv',
    funcao: 'Serviço',
    tipo: 'varchar',
    nome: 'codserv',
    tipoobject: 2,
    tamanho: 4,
    widthfield: 46,
    measure: '46rem',
    tabelaref: 'TB01005',
    widthname: 37,
    disabled: true,
    lancfield: true
  },
  {
    id: 1,
    campo: 'qtserv',
    funcao: 'Quantidade',
    tipo: 'numeric',
    nome: 'qtserv',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 10,
    measure: '10rem',
    disabled: true,
    lancfield: true
  },
  {
    id: 2,
    campo: 'prunit',
    funcao: 'Preço Unitário',
    tipo: 'numeric',
    nome: 'prunit',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 10,
    measure: '10rem',
    disabled: true,
    decimal: 2,
    lancfield: true
  },
  {
    id: 3,
    campo: 'cstpis',
    funcao: 'CST',
    tipo: 'varchar',
    nome: 'cstpis',
    tipoobject: 2,
    tamanho: 2,
    widthfield: 6,
    measure: '6rem',
    tabelaref: 'TB01052',
    widthname: 27,
    disabled: true,
    lancfield: true,
    findOnly: true
  },
  {
    id: 4,
    campo: 'aliqpis',
    funcao: '% Pis',
    tipo: 'numeric',
    nome: 'aliqpis',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 5,
    campo: 'cstcofins',
    funcao: 'CST',
    tipo: 'varchar',
    nome: 'cstcofins',
    tipoobject: 2,
    tamanho: 2,
    widthfield: 6,
    measure: '6rem',
    tabelaref: 'TB01053',
    widthname: 27,
    disabled: true,
    lancfield: true,
    findOnly: true
  },
  {
    id: 6,
    campo: 'aliqcofins',
    funcao: '% Cofins',
    tipo: 'numeric',
    nome: 'aliqcofins',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 7,
    campo: 'aliqiss',
    funcao: '% Iss',
    tipo: 'numeric',
    nome: 'aliqiss',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true,
    findOnly: true
  },
  {
    id: 8,
    campo: 'csll',
    funcao: '% Csll',
    tipo: 'numeric',
    nome: 'csll',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 9,
    campo: 'ir',
    funcao: '% Ir',
    tipo: 'numeric',
    nome: 'ir',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true
  },
  {
    id: 10,
    campo: 'inss',
    funcao: '% Inss',
    tipo: 'numeric',
    nome: 'inss',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true
  },
  {
    id: 11,
    campo: 'retpis',
    funcao: 'Ret. Pis',
    tipo: 'varchar',
    nome: 'retpis',
    tamanho: 1,
    tipoobject: 11,
    widthfield: 7,
    measure: '7.5rem',
    itens: 'Não,Sim',
    values: 'N,S',
    disabled: true,
    lancfield: true
  },
  {
    id: 12,
    campo: 'aliqpisret',
    funcao: '% Ret. Pis',
    tipo: 'numeric',
    nome: 'aliqpisret',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 13,
    campo: 'retcofins',
    funcao: 'Ret. Cofins',
    tipo: 'varchar',
    nome: 'retcofins',
    tamanho: 1,
    tipoobject: 11,
    widthfield: 7,
    measure: '7.5rem',
    itens: 'Não,Sim',
    values: 'N,S',
    disabled: true,
    lancfield: true
  },
  {
    id: 14,
    campo: 'aliqcofinsret',
    funcao: '% Ret. Cofins',
    tipo: 'numeric',
    nome: 'aliqcofinsret',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 15,
    campo: 'retiss',
    funcao: 'Ret. Iss',
    tipo: 'varchar',
    nome: 'retiss',
    tamanho: 1,
    tipoobject: 11,
    widthfield: 7,
    measure: '7.5rem',
    itens: 'Não,Sim',
    values: 'N,S',
    disabled: true,
    lancfield: true
  },
  {
    id: 16,
    campo: 'aliqissret',
    funcao: '% Ret. Iss',
    tipo: 'numeric',
    nome: 'aliqissret',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 17,
    campo: 'retcsll',
    funcao: 'Ret. Csll',
    tipo: 'varchar',
    nome: 'retcsll',
    tamanho: 1,
    tipoobject: 11,
    widthfield: 7,
    measure: '7.5rem',
    itens: 'Não,Sim',
    values: 'N,S',
    disabled: true,
    lancfield: true
  },
  {
    id: 18,
    campo: 'csllret',
    funcao: '% Ret. Csll',
    tipo: 'numeric',
    nome: 'csllret',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 19,
    campo: 'retir',
    funcao: 'Ret. Ir',
    tipo: 'varchar',
    nome: 'retir',
    tamanho: 1,
    tipoobject: 11,
    widthfield: 7,
    measure: '7.5rem',
    itens: 'Não,Sim',
    values: 'N,S',
    disabled: true,
    lancfield: true
  },
  {
    id: 20,
    campo: 'irret',
    funcao: '% Ret. Ir',
    tipo: 'numeric',
    nome: 'irret',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 21,
    campo: 'retinss',
    funcao: 'Ret. Inss',
    tipo: 'varchar',
    nome: 'retinss',
    tamanho: 1,
    tipoobject: 11,
    widthfield: 7,
    measure: '7.5rem',
    itens: 'Não,Sim',
    values: 'N,S',
    disabled: true,
    lancfield: true
  },
  {
    id: 22,
    campo: 'inssret',
    funcao: '% Ret. Inss',
    tipo: 'numeric',
    nome: 'inssret',
    tamanho: 9,
    tipoobject: 4,
    widthfield: 9,
    measure: '9rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  }
];

// Campos de Arredondamento (Serviços)
export const fieldsarredondaserv = [
  {
    id: 0,
    campo: 'manual',
    funcao: 'Arredondamento lançado MANUALMENTE',
    tipo: 'varchar',
    nome: 'manual',
    tamanho: 1,
    tipoobject: 9,
    widthfield: 70,
    measure: '70rem',
    valuechecked: 'S',
    valeunchecked: 'N',
    disabled: false,
    lancfield: true
  },
  {
    id: 1,
    campo: 'vlrpis',
    funcao: 'Valor Pis',
    tipo: 'numeric',
    nome: 'vlrpis',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 2,
    campo: 'vlrpisret',
    funcao: 'Valor Pis retido',
    tipo: 'numeric',
    nome: 'vlrpisret',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 3,
    campo: 'vlrcofins',
    funcao: 'R$ Cofins',
    tipo: 'numeric',
    nome: 'vlrcofins',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 4,
    campo: 'vlrcofinsret',
    funcao: 'R$ Cofins retido',
    tipo: 'numeric',
    nome: 'vlrcofinsret',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 5,
    campo: 'vlriss',
    funcao: 'Valor Iss',
    tipo: 'numeric',
    nome: 'vlriss',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 6,
    campo: 'vlrissret',
    funcao: 'Valor Iss retido',
    tipo: 'numeric',
    nome: 'vlrissret',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 7,
    campo: 'vlrcsll',
    funcao: 'Valor Csll',
    tipo: 'numeric',
    nome: 'vlrcsll',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 8,
    campo: 'vlrcsllret',
    funcao: 'Valor Csll retido',
    tipo: 'numeric',
    nome: 'vlrcsllret',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 9,
    campo: 'vlrir',
    funcao: 'Valor Ir',
    tipo: 'numeric',
    nome: 'vlrir',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 11,
    campo: 'vlrirret',
    funcao: 'Valor Ir retido',
    tipo: 'numeric',
    nome: 'vlrirret',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 11,
    campo: 'vlrinss',
    funcao: 'Valor Inss',
    tipo: 'numeric',
    nome: 'vlrinss',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  },
  {
    id: 12,
    campo: 'vlrinssret',
    funcao: 'Valor Inss retido',
    tipo: 'numeric',
    nome: 'vlrinssret',
    tamanho: 11,
    tipoobject: 4,
    widthfield: 11,
    measure: '11rem',
    decimal: 2,
    disabled: true,
    lancfield: true
  }
];

// Colunas nas Listagem (Parcelas)
export const columnspar = [
  { headerClassName: 'header-list', field: 'posicao', headerName: 'Nº', width: 60, type: 'number' },
  { headerClassName: 'header-list', field: 'doc', headerName: 'Documento', width: 140 },
  { headerClassName: 'header-list', field: 'dtvencfim', headerName: 'Vencimento', width: 110 },
  { headerClassName: 'header-list', field: 'nometipo', headerName: 'Tipo de Documento', width: 593 },
  { headerClassName: 'header-list', field: 'vlrdoc', headerName: 'Valor', width: 145, type: 'number', decimal: 2 }
];

// Campos de Lançamento (Parcelas)
export const fieldspar = [
  {
    id: 0,
    campo: 'posicao',
    funcao: 'Nº Parc.',
    tipo: 'numeric',
    nome: 'posicao',
    tamanho: 5,
    tipoobject: 4,
    widthfield: 5,
    measure: '5rem',
    disabled: true,
    lancfield: false
  },
  {
    id: 1,
    campo: 'doc',
    funcao: 'Nº Documento',
    tipo: 'varchar',
    nome: 'doc',
    tamanho: 20,
    tipoobject: 1,
    widthfield: 10,
    measure: '10rem',
    disabled: true,
    lancfield: true
  },
  {
    id: 2,
    campo: 'tipdoc',
    funcao: 'Tipo Documento',
    tipo: 'varchar',
    nome: 'tipdoc',
    tipoobject: 2,
    tamanho: 2,
    widthfield: 32,
    measure: '32rem',
    tabelaref: 'TB04003',
    widthname: 23,
    disabled: true,
    lancfield: true
  },

  {
    id: 3,
    campo: 'dtvenc',
    funcao: 'Vencimento',
    tipo: 'varchar',
    nome: 'doc',
    tamanho: 10,
    tipoobject: 5,
    widthfield: 10,
    measure: '10rem',
    disabled: true,
    lancfield: true
  },
  {
    id: 4,
    campo: 'vlrdoc',
    funcao: 'Valor',
    tipo: 'numeric',
    nome: 'vlrdoc',
    tamanho: 10,
    tipoobject: 4,
    widthfield: 10,
    measure: '10rem',
    disabled: true,
    lancfield: true,
    decimal: 2
  }
];
